### ISSUE TITLE
Randomize wallpaper choice like feh

### ISSUE THREAD

**Issue by rusmelezi** [stoeckmann/xwallpaper#11]
Can this be possible ?

**Comment by tmose1106** [comment]
I'm not really anyone associated with this project, but here is my two cents: that type of functionality can easily be scripted with Python or Bash. I feel that type of functionality is beyond the scope of this particular project. 

The reason being that the source of said "randomize wallpaper" could be a lot of things: local storage, over the web, etc. So I say take advantage of the ecosystem and try your own ad-hoc solution.

**Comment by stoeckmann** [comment]
I agree with @tmose1106 here:

xwallpaper is designed to do one thing: Setting wallpaper images per screen in an xrandr fashion. Randomly choosing which of the supplied arguments/files should be set feels like another abstraction layer. That one is about *which* image to show, not *how*. And the latter is what xwallpaper is all about.

As a side-note it was also a tough choice whether to implement the --daemon mode or not. Calling xwallpaper through an RandR listener daemon would have been nice, but the existing ones were not in the quality I expected. I could have written one on my own (naively believing I could do better without making my own faults, heh) but in fact the design implies that I keep a tool running with exec-permissions that gets triggered by X. Therefore --daemon was a more secure solution, because the sandbox prevents any form of execution.

If you can give me good reasons to re-evaluate your feature request in terms of simplicity or security, I will happily do so. But for now I would deny it due to previously stated reason.

**Comment by rusmelezi** [comment]
Thank you all for your response and appreciated for your great explanations. I got the philosophy behind why this project remain simple and minimal and decided to wrote my own wrapper around this project like @tmose1106 said.
