### ISSUE TITLE
Exit code 1 for "output not found"

### ISSUE THREAD

**Issue by matchatealeaf** [stoeckmann/xwallpaper#27]
The current exit code for "output not found" is 0.

For example:
```bash
$ xwallpaper --output HDMI1 --zoom ~/wall.png
xwallpaper: output HDMI1 not found/disconnected, ignoring
$ echo $?
0
```

Would it be better if this is changed to exit code 1 instead?
It will save a lot of trouble for scripting, e.g.
```bash
$ xwallpaper --output HDMI1 --zoom ~/wall.png || xwallpaper --output HDMI-1-1 --zoom ~/wall.png
```

**Comment by stoeckmann** [comment]
A return value of 1 for an operation which led to no result could be acceptable because it moves xwallpaper close to another common utility with such a behavior, namely grep. From its manual page:
```
EXIT STATUS
       Normally the exit status is 0 if a line is selected, 1 if no lines
       were selected, and 2 if an error occurred.
```
If at least one output was set, xwallpaper could be 0. If no output was set, it could return 1. And in any other error, it could be 2.

On the other hand it means that xwallpaper leaves the xrandr approach. If you would call something like `xrandr --output NONEXISTANT` then xrandr also returns with an stderr output and returns 0. You only get an exit code of 1 for invalid input or unavailable modes. "Invalid mode" does not sound like it matches the idea of "wallpaper cannot be set" because the wallpaper itself is valid and would be compatible with the output.

May I ask your setup in which xwallpaper should behave differently depending on the state of your outputs? You could merge these calls into a single one, but I guess that's not what you want (both outputs would be set).

And last but not least, when it comes to xrandr compatibility and scripting, I think you would have to use something like `xrandr --listactivemonitors  grep HDMI1 > /dev/null` to have an exit code of 0 if HDMI1 is available.

**Comment by matchatealeaf** [comment]
Thanks for the reply.
I didn't realise that I could put them in a single call:
```bash
$ xwallpaper --output HDMI1 --zoom ~/wall.png --output HDMI-1-1 --zoom ~/wall.png
```
This way it makes sense with an exit code of 0 if at least one of the output is valid.

My setup is not that special: Simply, I want my .profile to be able to call xwallpaper for a new TTY. In a new TTY, the output is HDMI-1-1, whereas the main TTY has a output of HDMI1, so I am scripting for both.

I was unaware of xrandr's approach. While I find grep's approach more intuitive, I think it is right to have the same behaviour as xrandr.

Also, thanks for the suggestion on xrandr scripting. Currently I am doing something along the lines of:
```bash
monitor=$(xrandr -q | grep ' connected' | awk '{print $1}')
xwallpaper --output $monitor --zoom ~/wall.png
```
Which solves my problem.
