### ISSUE TITLE
Wallpaper simply does not change

### ISSUE THREAD

**Issue by swindlesmccoop** [stoeckmann/xwallpaper#41]
```
[swindles@think420 ~]% xwallpaper --center /home/swindles/.config/wall/astolfo_white.jpg
[swindles@think420 ~]% xwallpaper --center /home/swindles/.config/wall/astolfo_white.jpg --debug
loading /home/swindles/.config/wall/astolfo_white.jpg
output detected: LVDS-1, 1600x900+1920+634
output detected: DP-1, 1920x1080+0+0
(randr) screen dimensions: 3520x1534+0+0
reusing atom pixmap (3520x1534)
composing /home/swindles/.config/wall/astolfo_white.jpg for LVDS-1 (area 1600x900+0+0) (mode 1)
xcb image (1600x900) to LVDS-1 (1600x900+1920+634)
put image request parameters:
maximum request length allowed for server (32 bits): 4194303
maximum length for row data: 16777188
length of rows in image: 6400
maximum height to send: 2621
put image (1600x900+0+0) to LVDS-1 (1600x900+1920+634)
composing /home/swindles/.config/wall/astolfo_white.jpg for DP-1 (area 1920x1080+0+0) (mode 1)
xcb image (1920x1080) to DP-1 (1920x1080+0+0)
put image request parameters:
maximum request length allowed for server (32 bits): 4194303
maximum length for row data: 16777188
length of rows in image: 7680
maximum height to send: 2184
put image (1920x1080+0+0) to DP-1 (1920x1080+0+0)
```
OS: Artix Linux
DE: KDE Plasma 5

I have two monitors and neither of them change

**Comment by stoeckmann** [comment]
Hi and thanks for giving detailed information, especially the desktop environment part.

I assume that you use the default window manager of KDE, which in turn means that the window manager itself does not use the X root pixmap for its background. The xwallpaper utility does set the root pixmap. So in turn, the result is not visible to the user. See #39, which is about GNOME but is equally true for KDE.

Since these desktop environments can run on X and Wayland, it makes total sense that they abstract away as much as they can. Unfortunately the effect is that tools like xwallpaper seem to not work properly.

**Comment by swindlesmccoop** [comment]
Alright, thanks for the explanation. Just another factor to aid my switch to DWM.
