### ISSUE TITLE
Wallpaper is reset when OS is restarted

### ISSUE THREAD

**Issue by dsentker** [stoeckmann/xwallpaper#49]
This works very well, but unfortunately the old background is set when the system is restarted. Any ideas for this?

**Comment by stoeckmann** [comment]
Hi Daniel,

this is expected behavior, because the X server itself is restarted as well.

I'd recommend to consult `.xinitrc`, `.xsession`, and `.xsessionrc` because it really depends on your way X starts, i.e. if it's done through a login manager (then it's xsession) or through startx (then it's xinitrc).

If you've found the correct file, add the `xwallpaper` along with its arguments into that file and it should work for you.

**Comment by dsentker** [comment]
Thank you, i didn't knew X server mechanics
